version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cpal
    versions:
    - 0.13.1
    - 0.13.2
  - dependency-name: nom
    versions:
    - 6.1.0
